---
version: "3.0"
services:
  app:
    build: .
    image: myhro/alpine-builder
    volumes:
      - ./.cache:/var/cache/apk
      - ./aports:/home/builder/aports
      - ./packages:/home/builder/packages
